// cursos/vue-react-angular-intro/vue-fw-intro/src/components/Hobbies.vue
<template>
  <div id="hobbies">
    <input type="text" v-model="newHobby">
    <button v-on:click="addNewHobby">Add new hobby</button>

    <p v-if="hobbies.length">New hobbies: {{ hobbies.length }}</p>
    <ul>
      <AddedHobby 
        v-for="hobby in hobbies"
        v-bind:key="hobby"
        v-bind:hobby="hobby"
        v-on:hobbyDeleted="deleteHobby($event)"/>
    </ul>

    <p v-if="deletedHobbies.length">Old hobbies: {{ deletedHobbies.length }}</p>
    <ul>
      <DeletedHobby
        v-for="deletedHobby in deletedHobbies"
        v-bind:key="deletedHobby"
        v-bind:hobby="deletedHobby"
        v-on:hobbyReadded="readdHobby($event)"/>
    </ul>
  </div>
</template>

<script>
import AddedHobby from '@/components/AddedHobby'
import DeletedHobby from '@/components/DeletedHobby'

export default {
  name: 'hobbies',
  data () {
    return {
      hobbies: ['Running', 'Dancing', 'Singing'],
      deletedHobbies: [],
      newHobby: ''
    }
  },
  methods: {
    addNewHobby () {
      this.hobbies.push(this.newHobby)
      this.newHobby = ''
    },
    deleteHobby (hobby) {
      var i = this.hobbies.indexOf(hobby)
      this.hobbies.splice(i, 1)
      this.deletedHobbies.push(hobby)
    },
    readdHobby (deletedHobby) {
      this.hobbies.push(deletedHobby)
      var i = this.deletedHobbies.indexOf(deletedHobby)
      this.deletedHobbies.splice(i, 1)
    }
  },
  components: {
    AddedHobby,
    DeletedHobby
  }
}
</script>

// cursos/vue-react-angular-intro/react-fw-intro/src/components/Hobbies.js
import React, { Component } from 'react';

import AddedHobby from './AddedHobby';
import DeletedHobby from './DeletedHobby';

class Hobbies extends Component {
  constructor(props) {
    super(props);
    this.state = {
      hobbies: ['Running', 'Dancing', 'Singing'],
      deletedHobbies: [],
      newHobby: ''
    };
  }

  addNewHobby() {
    this.setState(
      prevState => {
        return {
          hobbies: prevState.hobbies.concat(prevState.newHobby),
          newHobby: ''
        }
      }
    );
  }

  deleteHobby(hobby) {
    this.setState(
      prevState => {
        return {
          hobbies: prevState.hobbies.filter(h => h !== hobby),
          deletedHobbies: prevState.deletedHobbies.concat(hobby)
        }
      }
    );
  }

  readdHobby(deletedHobby) {
    this.setState(
      prevState => {
        return {
          hobbies: prevState.hobbies.concat(deletedHobby),
          deletedHobbies: prevState.deletedHobbies.filter(h => h !== deletedHobby)
        }
      }
    );
  }

  setNewHobby(newHobby) {
    this.setState({
      newHobby
    });
  }

  render() {
    return (
      <div id="hobbies">
        <input type="text" value={this.state.newHobby} 
          onChange={event => this.setNewHobby(event.target.value)}/>
        <button onClick={this.addNewHobby.bind(this)}>Add new hobby</button>

        {
          this.state.hobbies.length ? 
            <p>New hobbies: {this.state.hobbies.length}</p> : ''
        }

        <ul>
          {
            this.state.hobbies.map(
              hobby => 
                <AddedHobby 
                  key={hobby}
                  hobby={hobby} 
                  deleteHobby={this.deleteHobby.bind(this)}/>
            )
          }
        </ul>

        {
          this.state.deletedHobbies.length ? 
            <p>Old hobbies: {this.state.deletedHobbies.length}</p> : ''
        }

        <ul>
          {
            this.state.deletedHobbies.map(
              deletedHobby => 
                <DeletedHobby 
                  key={deletedHobby}
                  hobby={deletedHobby} 
                  readdHobby={this.readdHobby.bind(this)} />
            )
          }
        </ul>
      </div>
    );
  }
}

export default Hobbies;
