// cursos/vue-react-angular-intro/angular-fw-intro/src/app/menu/menu.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'mainmenu',
  templateUrl: './menu.component.html'
})
export class MenuComponent {
}

<nav id="menu">
  <hr/>
  <p>Menu</p>
  <ul>
    <li><a routerLink="/">Hobbies</a></li>
    <li><a routerLink="/helloworld">Hello World</a></li>
  </ul>
</nav>

// cursos/vue-react-angular-intro/react-fw-intro/src/components/Menu.js
import React from 'react';
import { Link } from 'react-router-dom';

function Menu() {
  return (
    <nav id="menu">
      <hr/>
      <p>Menu</p>
      <ul>
        <li><Link to="/">Hobbies</Link></li>
        <li><Link to="/helloworld">Hello World</Link></li>
      </ul>
    </nav>
  );
}

export default Menu;
