// cursos/vue-react-angular-intro/angular-fw-intro/src/app/hobbies/hobbies.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-hobbies',
  templateUrl: './hobbies.component.html'
})
export class HobbiesComponent {
  hobbies = ['Running', 'Dancing', 'Singing'];
  deletedHobbies : string[] = [];
  newHobby = '';

  onAddNewHobby () {
    this.hobbies.push(this.newHobby)
    this.newHobby = ''
  }

  onHobbyDeleted (hobby) {
    var i = this.hobbies.indexOf(hobby)
    this.hobbies.splice(i, 1)
    this.deletedHobbies.push(hobby)
  }

  onHobbyReadded (deletedHobby) {
    this.hobbies.push(deletedHobby)
    var i = this.deletedHobbies.indexOf(deletedHobby)
    this.deletedHobbies.splice(i, 1)
  }
}
<input type="text" [(ngModel)]="newHobby">
<button (click)="onAddNewHobby()">Add new hobby</button>

<p *ngIf="hobbies.length">New hobbies: {{ hobbies.length }}</p>
<ul>
  <app-addedHobby 
    *ngFor="let hobby of hobbies"
    [hobby]="hobby"
    (hobbyDeleted)="onHobbyDeleted($event)">
  </app-addedHobby>
</ul>

<p *ngIf="deletedHobbies.length">Old hobbies: {{ deletedHobbies.length }}</p>
<ul>
  <app-deletedHobby
    *ngFor="let deletedHobby of deletedHobbies"
    [hobby]="deletedHobby"
    (hobbyReadded)="onHobbyReadded($event)">
  </app-deletedHobby>
</ul>

// cursos/vue-react-angular-intro/vue-fw-intro/src/components/Hobbies.vue
<template>
  <div id="hobbies">
    <input type="text" v-model="newHobby">
    <button v-on:click="addNewHobby">Add new hobby</button>

    <p v-if="hobbies.length">New hobbies: {{ hobbies.length }}</p>
    <ul>
      <app-addedHobby 
        v-for="hobby in hobbies"
        v-bind:key="hobby"
        v-bind:hobby="hobby"
        v-on:hobbyDeleted="deleteHobby($event)"/>
    </ul>

    <p v-if="deletedHobbies.length">Old hobbies: {{ deletedHobbies.length }}</p>
    <ul>
      <app-deletedhobby
        v-for="deletedHobby in deletedHobbies"
        v-bind:key="deletedHobby"
        v-bind:hobby="deletedHobby"
        v-on:hobbyReadded="readdHobby($event)"/>
    </ul>
  </div>
</template>

<script>
import AddedHobby from '@/components/AddedHobby'
import DeletedHobby from '@/components/DeletedHobby'

export default {
  data () {
    return {
      hobbies: ['Running', 'Dancing', 'Singing'],
      deletedHobbies: [],
      newHobby: ''
    }
  },
  methods: {
    addNewHobby () {
      this.hobbies.push(this.newHobby)
      this.newHobby = ''
    },
    deleteHobby (hobby) {
      var i = this.hobbies.indexOf(hobby)
      this.hobbies.splice(i, 1)
      this.deletedHobbies.push(hobby)
    },
    readdHobby (deletedHobby) {
      this.hobbies.push(deletedHobby)
      var i = this.deletedHobbies.indexOf(deletedHobby)
      this.deletedHobbies.splice(i, 1)
    }
  },
  components: {
    'app-addedHobby': AddedHobby,
    'app-deletedHobby': DeletedHobby
  }
}
</script>
